### ISSUE TITLE
Дублирование экспортов component на страницах EditPage и LeaderboardPage

### ISSUE THREAD

**Issue by FellonOne** [PraktikumSeoulDevTeam/castleofghosts#30]
Получился конфликт имен в файле /src/pages/index.ts, из-за EditPage и LeaderboardPage
Так как у них стоит еспорт `export function component (...) {}`

**Comment by art4vm** [comment]
https://github.com/PraktikumSeoulDevTeam/castleofghosts/pull/31

**Comment by art4vm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BugFix:  Конфликт имен при экспорте компонент-страниц](https://trello.com/c/eHZYPv4f/66-bugfix-%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82-%D0%B8%D0%BC%D0%B5%D0%BD-%D0%BF%D1%80%D0%B8-%D1%8D%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86)
